[package]
name = "conman-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "conman-gateway"
path = "src/main.rs"

[dependencies]
argon2 = { version = "=0.5.3", default-features = false, features = ["alloc", "password-hash", "zeroize"] }
axum = { version = "=0.8.9", default-features = false, features = ["http1", "json", "ws"] }
getrandom = { version = "=0.4.3", default-features = false }
png = { version = "=0.18.1", default-features = false }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.150"
thiserror = "=2.0.18"
tokio = { version = "=1.52.3", default-features = false, features = ["fs", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
toml = { version = "=1.1.2", default-features = false, features = ["std", "serde", "parse"] }
url = { version = "=2.5.8", default-features = false, features = ["std"] }
uuid = { version = "=1.23.4", default-features = false, features = ["std", "v4"] }
zeroize = "=1.9.0"

[lints]
workspace = true
